<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var RubenRomao\BlogPosts\ViewModel\Post $postVm */
$postVm = $block->getData('post_vm');
$post = $postVm->getDetail();
?>
<div class="blog-post-detail">
    <h1><?= $escaper->escapeHtml($post->getTitle()) ?></h1>
    <p><em><?= $escaper->escapeHtml(__('Created at: %1', $post->getCreatedAt())) ?></em></p>
    <p><?= $escaper->escapeHtml($post->getContent(), ['em', 'p', 'strong']) ?></p>
</div>
