<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Rubenromao\BlogPosts\ViewModel\Post $postVm */
$postVm = $block->getData('post_vm');
?>
<div class="blog-post-list">
    <h1><?= $escaper->escapeHtml(__('Blog posts')) ?></h1>
    <ul>
        <?php foreach ($postVm->getList() as $post): ?>
            <li>
                <a href="<?= $escaper->escapeUrl($block->getUrl(
                    'blog/post/detail',
                    ['id' => $post->getData('id')]
                )) ?>">
                    <?= $escaper->escapeHtml($post->getData('title')) ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
    <p><?= $escaper->escapeHtml(__('Post count: %1', $postVm->getCount())) ?></p>
</div>
