<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var RubenRomao\BlogPosts\ViewModel\Post $postVm */
$postVm = $block->getData('post_vm');
?>
<div class="blog-post-sidebar">
    <p><strong><?= $escaper->escapeHtml(__('Other blog posts')) ?></strong></p>
    <ul>
        <?php
        foreach ($postVm->getList() as $post): ?>
            <li>
                <a href="<?= $escaper->escapeUrl($block->getUrl(
                    'blog/post/detail',
                    ['id' => $post->getData('id')]
                )) ?>">
                    <?= $escaper->escapeHtml($post->getData('title')) ?>
                </a>
            </li>
            <?php
        endforeach ?>
    </ul>
</div>
